name: EDPM Tests

on:
  # Trigger on push or pull request to any branch. Adjust if you want narrower triggers.
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (including test extras)
        run: |
          python -m pip install --upgrade pip
          # Install our package in editable mode plus `[test]` dependencies:
          python -m pip install .[test]

      - name: Run tests
        run: |
          pytest tests --maxfail=1 --disable-warnings -v
